---
language: python
python: "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt 
install:
  - pip install ansible ansible-lint
  - ansible --version
script:
  - ansible-lint tasks/main.yml
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check --list-tasks tests/test.yml -e "role_name=ansible-role-nginx" -e "hosts_group=hosts_group"
  - ansible-playbook -i inventory --connection=local --sudo -vvvv tests/test.yml -u root -e "role_name=ansible-role-nginx" -e "hosts_group=localhost"
  - >
      ansible-playbook -i inventory --connection=local --sudo -vvvv tests/test.yml -u root -e "role_name=ansible-role-nginx" -e "hosts_group=localhost"
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
  - cat /etc/nginx/nginx.conf
  - cat /etc/nginx/sites-enabled/sirbot
  - grep 'server_name sirbot.pyslackers.com;' /etc/nginx/sites-enabled/sirbot
  - sudo nginx -t
after_script:
  - ls -l /etc/nginx
  - ls -l /etc/nginx/*
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
