---
- name: install nginx
  apt:
    name: nginx
    state: latest
  notify:
    - start nginx

# - name: enable nginx in ufw
#   ufw:
#     rule: allow
#     name: 'Nginx Full'
#   notify:
#     - enable ufw

- import_tasks: ssl.yml
  with_dict: "{{ sites }}"
  when: item.value.ssl

- import_tasks: http.yml
